trigger:
  branches:
    include:
      - refs/tags/release-bindings-v*

pr: none

pool:
  vmImage: 'macOS-10.15'

variables:
  - group: nuget.org

steps:

- bash: |
    echo "##vso[task.setvariable variable=bindingsVersion]$(cat Xamarin.Amplitude.iOS/Xamarin.Amplitude.iOS.csproj | grep '<Version>' | awk -F '[<>]' '{print $3}')"

- bash: |
    echo "##vso[build.updatebuildnumber]xamarin-amplitude-ios-bindings-$(Build.SourceBranchName)-$(Build.BuildId)"

- bash: |
    if [[ "$(Build.SourceBranchName)" != *"$(bindingsVersion)" ]]; then
      echo "mismatch between tag $(Build.SourceBranchName) and nuget version $(bindingsVersion)"
      exit 1
    fi

- bash: |
    cd Xamarin.Amplitude.iOS
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release

- bash: |
    dotnet nuget push Xamarin.Amplitude.iOS/nugetoutput/Xamarin.Amplitude.iOS.*.nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_thisisthekap'
    repositoryName: 'thisisthekap/Xamarin.Amplitude.iOS'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.SourceBranchName)'
    title: 'Xamarin.Amplitude.iOS Bindings $(bindingsVersion)'
    assets: 'Xamarin.Amplitude.iOS/nugetoutput/Xamarin.Amplitude.iOS.*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
